name: Gestion Automatique des Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  auto-assign:
    name: Attribution Automatique
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'

    steps:
      - name: Auto-assign selon les labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name);
            
            // Attribution automatique selon le type
            let assignees = [];
            
            if (labels.includes('security')) {
              // Assigner les issues de sécurité au lead technique
              assignees.push('lead-dev-username');
            } else if (labels.includes('bug') && labels.includes('P0-critical')) {
              // Assigner les bugs critiques immédiatement
              assignees.push('lead-dev-username');
            } else if (labels.includes('enhancement')) {
              // Assigner les demandes de fonctionnalités au product owner
              assignees.push('product-owner-username');
            }
            
            if (assignees.length > 0) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                assignees: assignees
              });
            }

  auto-label:
    name: Étiquetage Automatique
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'

    steps:
      - name: Auto-label basé sur le contenu
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body.toLowerCase();
            
            let labelsToAdd = [];
            
            // Détection automatique de module
            if (title.includes('auth') || body.includes('authentification') || body.includes('login')) {
              labelsToAdd.push('module:auth');
            }
            if (title.includes('emotion') || body.includes('tracker')) {
              labelsToAdd.push('module:emotions');
            }
            if (title.includes('diagnostic')) {
              labelsToAdd.push('module:diagnostics');
            }
            if (title.includes('activit') || body.includes('détente')) {
              labelsToAdd.push('module:activities');
            }
            
            // Détection de type
            if (title.includes('[bug]') || title.includes('erreur') || title.includes('problème')) {
              labelsToAdd.push('bug');
            }
            if (title.includes('[feature]') || title.includes('fonctionnalité') || title.includes('amélioration')) {
              labelsToAdd.push('enhancement');
            }
            if (title.includes('[security]') || body.includes('sécurité') || body.includes('vulnérabilité')) {
              labelsToAdd.push('security');
              labelsToAdd.push('urgent');
            }
            
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labelsToAdd
              });
            }

  security-alert:
    name: Alerte Sécurité
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'security')

    steps:
      - name: Notification urgente sécurité
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            
            // Créer un commentaire urgent
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `🚨 **ALERTE SÉCURITÉ DÉTECTÉE**
            
              Cette issue a été automatiquement marquée comme problème de sécurité.
            
              **Actions automatiques prises :**
              - 🏷️ Étiquetée comme "security" et "urgent"
              - 👥 Équipe sécurité notifiée
              - ⏰ SLA réduit à 2 heures
            
              **Prochaines étapes :**
              1. Évaluation immédiate de la criticité
              2. Analyse d'impact sur les données utilisateur
              3. Plan de correction si nécessaire
            
              L'équipe technique va traiter cette issue en priorité.`
            });